### ISSUE TITLE
in subclass such as publisher the properties of parent class are missing!

### ISSUE THREAD

**Issue by SepidehAlassi** [dasch-swiss/beol#54]
The property containing the name of the publisher is not represented. see
https://beol-test.dasch.swiss/person/http:%2F%2Frdfh.ch%2F0802%2F-3rn5GslRuet8OOLf21fzw

I believe the current template just shows the immediate properties of a resource. However Publisher is subClass of Organization resource class. The properties which Publisher class inherits from Organization such as "hasName", "comment" should also be presented for Publisher!

**Comment by flavens** [comment]
@SepidehAlassi in the component Person, I have already added the properties "#hasName" and "#publisherHasLocation", "#comment" was in the list before. You can check the file person.component.ts.
The label is displayed (center title) instead of the name because the label contains the name.
I added a if/else condition in case the label does not exist, then the name is displayed.

 If I am wrong, could you provide me one or two examples and the name of the properties?

**Comment by SepidehAlassi** [comment]
@flavens well in 95% of cases publisher is not a person, but it is an organization. Although the name is part of label, but it is not always the case. Sometime in label, the name of publisher is abbreviated. Therefore the property "hasName" should be visible to user. 
For example in new GUI
<img width="489" alt="screenshot 2018-10-29 11 10 22" src="https://user-images.githubusercontent.com/8567642/47646285-5e9aff80-db6b-11e8-8890-7f5fdb534dce.png">
publisher's name should be shown as a separate property like
<img width="172" alt="screenshot 2018-10-29 11 11 53" src="https://user-images.githubusercontent.com/8567642/47646329-825e4580-db6b-11e8-96bc-2a2bdeb142f9.png">
